// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwBYmOl_jNifWvDa4urdKN4yBGfETyM8M',
    appId: '1:364844884981:web:3c1000b2eb21911348f6bc',
    messagingSenderId: '364844884981',
    projectId: 'messageapp-51ce8',
    authDomain: 'messageapp-51ce8.firebaseapp.com',
    storageBucket: 'messageapp-51ce8.appspot.com',
    measurementId: 'G-F0Q5RV0TNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLKCKRssKvhjb-obtdYerJ21erImEJ-y8',
    appId: '1:364844884981:android:e715e8869bf5ca9b48f6bc',
    messagingSenderId: '364844884981',
    projectId: 'messageapp-51ce8',
    storageBucket: 'messageapp-51ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcO2P4zSL4zYE4qWGvj25pdEpLOlHs_Lk',
    appId: '1:364844884981:ios:f82b05ac494c73f048f6bc',
    messagingSenderId: '364844884981',
    projectId: 'messageapp-51ce8',
    storageBucket: 'messageapp-51ce8.appspot.com',
    androidClientId: '364844884981-fi6f578ls970vsn8s6b2l4s2agipn3d6.apps.googleusercontent.com',
    iosClientId: '364844884981-89spgfacecirthjgnk7tlia8tq8f8f3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcO2P4zSL4zYE4qWGvj25pdEpLOlHs_Lk',
    appId: '1:364844884981:ios:786db6b5103a252048f6bc',
    messagingSenderId: '364844884981',
    projectId: 'messageapp-51ce8',
    storageBucket: 'messageapp-51ce8.appspot.com',
    androidClientId: '364844884981-fi6f578ls970vsn8s6b2l4s2agipn3d6.apps.googleusercontent.com',
    iosClientId: '364844884981-0pdbrg8npnt7n4vmr5shs5hu32kchdnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp.RunnerTests',
  );
}
